<template>
  <div>
    Planet
    <select style="display: inline">
      <option v-for="(planet, pIndex) in planets" :key="pIndex">
        {{ planet.title }}
      </option>
    </select>
  </div>
  <div>
    Continent
    <select style="display: inline">
      <option v-for="(continent, cIndex) in continents" :key="cIndex">
        {{ continent.title }}
      </option>
    </select>
  </div>
  <div>
    Country
    <select style="display: inline">
      <option v-for="country in countries" :key="country.code">
        {{ country.title }}
      </option>
    </select>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "OrderView",
  data() {
    return {
      planets: [
        {
          title: "Io",
        },
        {
          title: "Earth",
        },
        {
          title: "Mars",
        },
        {
          title: "Moon",
        },
      ],
      continents: [
        {
          title: "Africa",
        },
        {
          title: "Antartica",
        },
        {
          title: "Asia",
        },
        {
          title: "Australia",
        },
        {
          title: "Europe",
        },
        {
          title: "North America",
        },
        {
          title: "South America",
        },
      ],
      countries: [
        { code: 1, title: "Afghanistan" },
        { code: 2, title: "Albania" },
        { code: 3, title: "Algeria" },
        { code: 4, title: "Andorra" },
        { code: 5, title: "Angola" },
        { code: 6, title: "Antigua and Barbuda" },
        { code: 7, title: "Argentina" },
        { code: 8, title: "Armenia" },
        { code: 9, title: "Australia" },
        { code: 10, title: "Austria" },
        { code: 11, title: "Azerbaijan" },
        { code: 12, title: "Bahamas" },
        { code: 13, title: "Bahrain" },
        { code: 14, title: "Bangladesh" },
        { code: 15, title: "Barbados" },
        { code: 16, title: "Belarus" },
        { code: 17, title: "Belgium" },
        { code: 18, title: "Belize" },
        { code: 19, title: "Benin" },
        { code: 20, title: "Bhutan" },
        { code: 21, title: "Bolivia" },
        { code: 22, title: "Bosnia and Herzegovina" },
        { code: 23, title: "Botswana" },
        { code: 24, title: "Brazil" },
        { code: 25, title: "Brunei" },
        { code: 26, title: "Bulgaria" },
        { code: 27, title: "Burkina Faso" },
        { code: 28, title: "Burundi" },
        { code: 30, title: "Cabo Verde" },
        { code: 31, title: "Cambodia" },
        { code: 32, title: "Cameroon" },
        { code: 33, title: "Canada" },
        { code: 34, title: "Central African Republic" },
        { code: 35, title: "Chad" },
        { code: 36, title: "Chile" },
        { code: 37, title: "China" },
        { code: 38, title: "Colombia" },
        { code: 39, title: "Comoros" },
        { code: 41, title: "Costa Rica" },
        { code: 42, title: "Croatia" },
        { code: 43, title: "Cuba" },
        { code: 44, title: "Cyprus" },
        { code: 45, title: "Czechia (Czech Republic)" },
        { code: 46, title: "Democratic Republic of the Congo" },
        { code: 47, title: "Denmark" },
        { code: 48, title: "Djibouti" },
        { code: 49, title: "Dominica" },
        { code: 50, title: "Dominican Republic" },
        { code: 51, title: "Ecuador" },
        { code: 52, title: "Egypt" },
        { code: 53, title: "El Salvador" },
        { code: 54, title: "Equatorial Guinea" },
        { code: 55, title: "Eritrea" },
        { code: 56, title: "Estonia" },
        { code: 58, title: "Ethiopia" },
        { code: 59, title: "Fiji" },
        { code: 60, title: "Finland" },
        { code: 61, title: "France" },
        { code: 62, title: "Gabon" },
        { code: 63, title: "Gambia" },
        { code: 64, title: "Georgia" },
        { code: 65, title: "Germany" },
        { code: 66, title: "Ghana" },
        { code: 67, title: "Greece" },
        { code: 68, title: "Grenada" },
        { code: 69, title: "Guatemala" },
        { code: 70, title: "Guinea" },
        { code: 72, title: "Guyana" },
        { code: 73, title: "Haiti" },
        { code: 74, title: "Holy See" },
        { code: 75, title: "Honduras" },
        { code: 76, title: "Hungary" },
        { code: 77, title: "Iceland" },
        { code: 78, title: "India" },
        { code: 79, title: "Indonesia" },
        { code: 80, title: "Iran" },
        { code: 81, title: "Iraq" },
        { code: 82, title: "Ireland" },
        { code: 83, title: "Israel" },
        { code: 84, title: "Italy" },
        { code: 85, title: "Jamaica" },
        { code: 86, title: "Japan" },
        { code: 87, title: "Jordan" },
        { code: 88, title: "Kazakhstan" },
        { code: 89, title: "Kenya" },
        { code: 90, title: "Kiribati" },
        { code: 91, title: "Kuwait" },
        { code: 92, title: "Kyrgyzstan" },
        { code: 93, title: "Laos" },
        { code: 94, title: "Latvia" },
        { code: 95, title: "Lebanon" },
        { code: 96, title: "Lesotho" },
        { code: 97, title: "Liberia" },
        { code: 98, title: "Libya" },
        { code: 99, title: "Liechtenstein" },
        { code: 100, title: "Lithuania" },
        { code: 101, title: "Luxembourg" },
        { code: 102, title: "Madagascar" },
        { code: 103, title: "Malawi" },
        { code: 104, title: "Malaysia" },
        { code: 105, title: "Maldives" },
        { code: 106, title: "Mali" },
        { code: 107, title: "Malta" },
        { code: 108, title: "Marshall Islands" },
        { code: 109, title: "Mauritania" },
        { code: 110, title: "Mauritius" },
        { code: 111, title: "Mexico" },
        { code: 112, title: "Micronesia" },
        { code: 113, title: "Moldova" },
        { code: 114, title: "Monaco" },
        { code: 115, title: "Mongolia" },
        { code: 116, title: "Montenegro" },
        { code: 117, title: "Morocco" },
        { code: 118, title: "Mozambique" },
        { code: 119, title: "Myanmar (formerly Burma)" },
        { code: 120, title: "Namibia" },
        { code: 121, title: "Nauru" },
        { code: 122, title: "Nepal" },
        { code: 123, title: "Netherlands" },
        { code: 124, title: "New Zealand" },
        { code: 125, title: "Nicaragua" },
        { code: 126, title: "Niger" },
        { code: 127, title: "Nigeria" },
        { code: 128, title: "North Korea" },
        { code: 129, title: "North Macedonia" },
        { code: 130, title: "Norway" },
        { code: 131, title: "Oman" },
        { code: 132, title: "Pakistan" },
        { code: 133, title: "Palau" },
        { code: 134, title: "Palestine State" },
        { code: 135, title: "Panama" },
        { code: 136, title: "Papua New Guinea" },
        { code: 137, title: "Paraguay" },
        { code: 138, title: "Peru" },
        { code: 139, title: "Philippines" },
        { code: 140, title: "Poland" },
        { code: 141, title: "Portugal" },
        { code: 142, title: "Qatar" },
        { code: 143, title: "Romania" },
        { code: 144, title: "Russia" },
        { code: 145, title: "Rwanda" },
        { code: 146, title: "Saint Kitts and Nevis" },
        { code: 147, title: "Saint Lucia" },
        { code: 148, title: "Saint Vincent and the Grenadines" },
        { code: 149, title: "Samoa" },
        { code: 150, title: "San Marino" },
        { code: 151, title: "Sao Tome and Principe" },
        { code: 152, title: "Saudi Arabia" },
        { code: 153, title: "Senegal" },
        { code: 154, title: "Serbia" },
        { code: 155, title: "Seychelles" },
        { code: 156, title: "Sierra Leone" },
        { code: 157, title: "Singapore" },
        { code: 158, title: "Slovakia" },
        { code: 159, title: "Slovenia" },
        { code: 160, title: "Solomon Islands" },
        { code: 161, title: "Somalia" },
        { code: 162, title: "South Africa" },
        { code: 163, title: "South Korea" },
        { code: 164, title: "South Sudan" },
        { code: 165, title: "Spain" },
        { code: 166, title: "Sri Lanka" },
        { code: 167, title: "Sudan" },
        { code: 168, title: "Suriname" },
        { code: 169, title: "Sweden" },
        { code: 170, title: "Switzerland" },
        { code: 171, title: "Syria" },
        { code: 172, title: "Tajikistan" },
        { code: 173, title: "Tanzania" },
        { code: 174, title: "Thailand" },
        { code: 176, title: "Togo" },
        { code: 177, title: "Tonga" },
        { code: 178, title: "Trinidad and Tobago" },
        { code: 179, title: "Tunisia" },
        { code: 180, title: "Turkey" },
        { code: 181, title: "Turkmenistan" },
        { code: 182, title: "Tuvalu" },
        { code: 183, title: "Uganda" },
        { code: 184, title: "Ukraine" },
        { code: 185, title: "United Arab Emirates" },
        { code: 186, title: "United Kingdom" },
        { code: 187, title: "United States of America" },
        { code: 188, title: "Uruguay" },
        { code: 189, title: "Uzbekistan" },
        { code: 190, title: "Vanuatu" },
        { code: 191, title: "Venezuela" },
        { code: 192, title: "Vietnam" },
        { code: 193, title: "Yemen" },
        { code: 194, title: "Zambia" },
      ],
      selected: -1,
    };
  },
});
</script>
